version: '2'
services:
  web: &webimage
    build: .
    volumes:
      - /home/docker/docker_dir/benchmark_es_bundle:/bundle
      - .:/myapp
    links:
      - elasticsearch
    environment:
      - ES_URL=elasticsearch:9200
      - ES_INDEX=benchmark_es

  elasticsearch:
    image: elasticsearch:2.2.0
    expose:
      - "9200"
    ports:
      - "9200:9200"
    command: elasticsearch -Des.network.bind_host=0.0.0.0
